name: gg_supply_chain
description: Supply Chain (SC) is a data flow and state management architecture.
version: 1.0.0
repository: https://github.com/inlavigo/gg_supply_chain

environment:
  sdk: ">=3.2.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  gg_once_per_cycle: ^1.3.1
  gg_fake_stopwatch: ^1.1.0
  gg_fake_timer: 1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  coverage: ^1.7.1
  fake_async: ^1.3.1
  pana: ^0.21.45
  args: ^2.4.2
