name: supply_chain
description: Supply Chain (SC) is a data flow and state management architecture.
version: 1.0.2
repository: https://github.com/inlavigo/supply_chain

environment:
  sdk: ">=3.2.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  gg_once_per_cycle: ^1.3.1
  gg_fake_stopwatch: ^1.1.0
  gg_fake_timer: ^1.0.3
  gg_log: ^1.0.6
  gg_cache: ^1.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  fake_async: ^1.3.1