flowchart TD
  subgraph level1_90["level1"]
    c0_86["c0"]
    c1_87["c1"]
    subgraph level0_92["level0"]
      x_85["x"]
    end
  end

  x_85 --> c0_86;
  x_85 --> c1_87;

  classDef highlight fill:#FFFFAA,stroke:#333;