flowchart TD
  subgraph level1_76["level1"]
    s1_68["s1"]
    s0_69["s0"]
    subgraph level0_78["level0"]
      x_70["x"]
    end
  end

  s1_68 --> x_70;
  s0_69 --> x_70;

  classDef highlight fill:#FFFFAA,stroke:#333;