flowchart TD
  subgraph level1_230["level1"]
    s1_233["s1"]
    s0_234["s0"]
    c0_236["c0"]
    c1_237["c1"]
    subgraph level0_232["level0"]
    end
  end


  classDef highlight fill:#FFFFAA,stroke:#333;