flowchart TD
  subgraph example_266["example"]
    subgraph a_268["a"]
      subgraph b_270["b"]
        subgraph c_272["c"]
        end
      end
    end
  end


  classDef highlight fill:#FFFFAA,stroke:#333;