flowchart TD
  subgraph level1_202["level1"]
    s1_203["s1"]
    s0_204["s0"]
    c0_206["c0"]
    c1_207["c1"]
    subgraph level0_204["level0"]
      x_205["x"]
    end
  end

  s1_203 --> x_205;
  s0_204 --> x_205;
  x_205 --> c0_206;
  x_205 --> c1_207;

  classDef highlight fill:#FFFFAA,stroke:#333;