flowchart TD
  subgraph level1_90["level1"]
    s1_83["s1"]
    s0_84["s0"]
    subgraph level0_92["level0"]
      x_85["x"]
    end
  end

  s1_83 --> x_85;
  s0_84 --> x_85;

  classDef highlight fill:#FFFFAA,stroke:#333;