flowchart TD
  subgraph example_252["example"]
    subgraph a_254["a"]
      subgraph b_256["b"]
        subgraph c_258["c"]
        end
      end
    end
  end


  classDef highlight fill:#FFFFAA,stroke:#333;