// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:test/test.dart';

void main() {
  test('Create README.md', () async {
    // Insert hint
    var result = '<!-- Don\'t edit. Generated by readme_test.dart -->';

    // Read template
    final template = await File(
      'test/readmes/README_TEMPLATE.md',
    ).readAsString();
    result += '\n$template';

    // Read all INSERT FILE patterns
    final insertFileRegExp = RegExp(r'INSERT (.+)');
    final matches = insertFileRegExp.allMatches(result);

    for (final match in matches) {
      final fileName = match.group(1);
      if (fileName != null) {
        final fileContent = await File(fileName).readAsString();
        result = result.replaceFirst('INSERT $fileName', fileContent);
      }
    }

    // Write result to README.md
    await File('README.md').writeAsString(result);
  });
}
